Repository GraphicEdit/BlueProject, pull requests merged in 2020-04, with the labels that each got.

#134 ExplosionFX
  BlueProject/Assets/ExplosionVFX.meta
  BlueProject/Assets/ExplosionVFX/Materials.meta
  BlueProject/Assets/ExplosionVFX/Materials/Debris.png
  BlueProject/Assets/ExplosionVFX/Materials/Debris.png.meta
  BlueProject/Assets/ExplosionVFX/Materials/DebrisParticle.mat
  BlueProject/Assets/ExplosionVFX/Materials/DebrisParticle.mat.meta
  BlueProject/Assets/ExplosionVFX/Materials/Embers.mat
  BlueProject/Assets/ExplosionVFX/Materials/Embers.mat.meta
  BlueProject/Assets/ExplosionVFX/Materials/EnergyShockwave.mat
  BlueProject/Assets/ExplosionVFX/Materials/EnergyShockwave.mat.meta
  BlueProject/Assets/ExplosionVFX/Materials/Explosion.mat
  BlueProject/Assets/ExplosionVFX/Materials/Explosion.mat.meta
  BlueProject/Assets/ExplosionVFX/Materials/Explosion.png
  BlueProject/Assets/ExplosionVFX/Materials/Explosion.png.meta
  BlueProject/Assets/ExplosionVFX/Materials/ExplosionDistortion.mat
  BlueProject/Assets/ExplosionVFX/Materials/ExplosionDistortion.mat.meta
  BlueProject/Assets/ExplosionVFX/Materials/ExplosionEmission.png
  BlueProject/Assets/ExplosionVFX/Materials/ExplosionEmission.png.meta
  BlueProject/Assets/ExplosionVFX/Materials/RoundSoftParticle.png
  BlueProject/Assets/ExplosionVFX/Materials/RoundSoftParticle.png.meta
  BlueProject/Assets/ExplosionVFX/Materials/SmokeDark.mat
  BlueProject/Assets/ExplosionVFX/Materials/SmokeDark.mat.meta
  BlueProject/Assets/ExplosionVFX/Materials/SmokePuff01.png
  BlueProject/Assets/ExplosionVFX/Materials/SmokePuff01.png.meta
  BlueProject/Assets/ExplosionVFX/Materials/SphereNormal.png
  BlueProject/Assets/ExplosionVFX/Materials/SphereNormal.png.meta
  BlueProject/Assets/ExplosionVFX/Materials/shockwave.tif
  BlueProject/Assets/ExplosionVFX/Materials/shockwave.tif.meta
  BlueProject/Assets/ExplosionVFX/VFX_BigExplosion.prefab
  BlueProject/Assets/ExplosionVFX/VFX_BigExplosion.prefab.meta
  BlueProject/Assets/ExplosionVFX/VFX_SmallExplosion.prefab
  BlueProject/Assets/ExplosionVFX/VFX_SmallExplosion.prefab.meta
  BlueProject/Assets/ExplosionVFX/VFX_TinyExplosion.prefab
  BlueProject/Assets/ExplosionVFX/VFX_TinyExplosion.prefab.meta
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Scenes/Level-1.unity
Labels: Visual

#133 Temporary power ups
  BlueProject/Assets/Prefabs/Collectable.meta
  BlueProject/Assets/Prefabs/Collectable/CollectableTemplate.prefab
  BlueProject/Assets/Prefabs/Collectable/CollectableTemplate.prefab.meta
  BlueProject/Assets/Prefabs/Collectable/HealthPickUp Variant.prefab
  BlueProject/Assets/Prefabs/Collectable/HealthPickUp Variant.prefab.meta
  BlueProject/Assets/Prefabs/Collectable/RocketPickUp Variant.prefab
  BlueProject/Assets/Prefabs/Collectable/RocketPickUp Variant.prefab.meta
  BlueProject/Assets/Scenes/Level-1.unity
  BlueProject/Assets/Scripts/Drops.meta
  BlueProject/Assets/Scripts/Drops/Collectable.cs
  BlueProject/Assets/Scripts/Drops/Collectable.cs.meta
  BlueProject/Assets/Scripts/Drops/PowerUpList.cs
  BlueProject/Assets/Scripts/Drops/PowerUpList.cs.meta
  BlueProject/Assets/Scripts/Health.cs
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Scripts/Projectile.cs
  BlueProject/Assets/Scripts/ShootLaser.cs
  BlueProject/Assets/Scripts/ShootRocket.cs
  BlueProject/Assets/Sprites/powerup.png
  BlueProject/Assets/Sprites/powerup.png.meta
  BlueProject/ProjectSettings/TagManager.asset
Labels: Coding

#135 Rocket Trail
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Scenes/Level-1.unity
  BlueProject/Assets/Sprites/Rocket.png.meta
Labels: Visual

#138 BugFixed
  BlueProject/Assets/ExplosionVFX/VFX_BigExplosion.prefab
  BlueProject/Assets/ExplosionVFX/VFX_SmallExplosion.prefab
  BlueProject/Assets/ExplosionVFX/VFX_TinyExplosion.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Scenes/Level-1.unity
  BlueProject/Assets/Scripts/Projectile.cs
Labels: BUG

#146 ShieldTouch sfx
  BlueProject/Assets/Sound/Effects/ShieldTouch1.wav
  BlueProject/Assets/Sound/Effects/ShieldTouch2.wav
  BlueProject/Assets/Sound/Effects/ShieldTouch3.wav
  BlueProject/Assets/Sound/Effects/ShieldTouch4.wav
  BlueProject/Assets/Sound/Effects/ShieldTouch5.wav
  BlueProject/Assets/Sound/Effects/ShieldTouch6.wav
  BlueProject/Assets/Sound/Effects/ShieldTouch7.wav
Labels: Audio, SoundFX
