Repository GraphicEdit/BlueProject, pull requests merged in 2020-03, with the labels that each got.

#39 simple Control
  BlueProject/Assets/Art/TestArt2.png
  BlueProject/Assets/Code/TestCode.cs
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scenes/Main.unity.meta
  BlueProject/Assets/Scripts.meta
  BlueProject/Assets/Scripts/GameController.cs
  BlueProject/Assets/Scripts/GameController.cs.meta
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Scripts/Player.cs.meta
  BlueProject/Assets/Sprites.meta
  BlueProject/Assets/Sprites/ship.png
  BlueProject/Assets/Sprites/ship.png.meta
  BlueProject/ProjectSettings/TagManager.asset
Labels: Coding

#41 New scrolling background script and improved movement speed to enchan…
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/Background.cs
  BlueProject/Assets/Scripts/Background.cs.meta
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Sprites/Materials.meta
  BlueProject/Assets/Sprites/Materials/BG-tile_nebula.mat
  BlueProject/Assets/Sprites/Materials/BG-tile_nebula.mat.meta
Labels: Coding

#43 Coding repo
  BlueProject/Assets/Scenes/Main.unity
Labels: Coding

#46 Space Items
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/SpaceItemCONTROL.prefab
  BlueProject/Assets/Prefabs/SpaceItemCONTROL.prefab.meta
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/SpaceItemScroll.cs
  BlueProject/Assets/Scripts/SpaceItemScroll.cs.meta
  BlueProject/Assets/Scripts/SpaceItems.cs
  BlueProject/Assets/Scripts/SpaceItems.cs.meta
  BlueProject/Assets/Sprites/SpaceItem.png
  BlueProject/Assets/Sprites/SpaceItem.png.meta
Labels: Coding

#53 Code optimization
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Scripts/SpaceItems.cs
Labels: Coding

#55 Player's rocket
  BlueProject/Assets/Prefabs/Player'sRocket.prefab
  BlueProject/Assets/Prefabs/Player'sRocket.prefab.meta
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/SpaceItemCONTROL.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/Rocket.cs
  BlueProject/Assets/Scripts/Rocket.cs.meta
  BlueProject/Assets/Scripts/ShootRocket.cs
  BlueProject/Assets/Scripts/ShootRocket.cs.meta
Labels: Coding

#57 Rocket
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab.meta
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Sprites/Rocket.png
  BlueProject/Assets/Sprites/Rocket.png.meta
Labels: Coding, Visual

#59 LaserFire
  BlueProject/Assets/Sprites/BG-tile_nebula.png.meta
  BlueProject/Assets/Sprites/LaserFire.png
  BlueProject/Assets/Sprites/SpaceItem.png.meta
  BlueProject/Assets/Sprites/ship.png.meta
Labels: Visual

#63 RocketCooldown and some tweaks
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Scripts/ShootRocket.cs
  BlueProject/Assets/Sprites/LaserFire.png.meta
Labels: Coding

#64 LaserShoot
  BlueProject/Assets/Animation.meta
  BlueProject/Assets/Animation/LaserFire.controller
  BlueProject/Assets/Animation/LaserFire.controller.meta
  BlueProject/Assets/Animation/LaserStretch.anim
  BlueProject/Assets/Animation/LaserStretch.anim.meta
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersLaser.prefab
  BlueProject/Assets/Prefabs/PlayersLaser.prefab.meta
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/Laser.cs
  BlueProject/Assets/Scripts/Laser.cs.meta
  BlueProject/Assets/Scripts/ShootLaser.cs
  BlueProject/Assets/Scripts/ShootLaser.cs.meta
Labels: Coding

#68 EnemyDrone-PlaceHolder
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab.meta
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Sprites/EnemyDroneA.png
  BlueProject/Assets/Sprites/EnemyDroneA.png.meta
Labels: 2D Sprite, Visual

#72 Stage clear
  BlueProject/Assets/Scripts/GameController.cs
Labels: Coding

#77 EnemyMoves
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/EnemyMovement.cs
  BlueProject/Assets/Scripts/EnemyMovement.cs.meta
  BlueProject/Assets/Scripts/EnemyMoves.meta
  BlueProject/Assets/Scripts/EnemyMoves/EnemyMoves.cs
  BlueProject/Assets/Scripts/EnemyMoves/EnemyMoves.cs.meta
  BlueProject/Assets/Scripts/EnemyMoves/Forward1.asset
  BlueProject/Assets/Scripts/EnemyMoves/Forward1.asset.meta
  BlueProject/Assets/Scripts/EnemyMoves/TurnLeft45.asset
  BlueProject/Assets/Scripts/EnemyMoves/TurnLeft45.asset.meta
  BlueProject/Assets/Scripts/EnemyMoves/TurnLeft90.asset
  BlueProject/Assets/Scripts/EnemyMoves/TurnLeft90.asset.meta
  BlueProject/Assets/Scripts/EnemyMoves/TurnRight45.asset
  BlueProject/Assets/Scripts/EnemyMoves/TurnRight45.asset.meta
  BlueProject/Assets/Scripts/EnemyMoves/TurnRight90.asset
  BlueProject/Assets/Scripts/EnemyMoves/TurnRight90.asset.meta
Labels: Coding

#81 Add files via upload
  BlueProject/Assets/Art/game-over.ttf
Labels: UI / UX

#83 Pooling sytem
  BlueProject/Assets/Art/game-over.ttf.meta
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/Laser.cs
  BlueProject/Assets/Scripts/Pooler.meta
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManager.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManager.cs.meta
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerScriptableObject.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerScriptableObject.cs.meta
  BlueProject/Assets/Scripts/Pooler/LaserPooler.asset
  BlueProject/Assets/Scripts/Pooler/LaserPooler.asset.meta
  BlueProject/Assets/Scripts/ShootLaser.cs
  BlueProject/Assets/Sound/Music.meta
  BlueProject/Assets/Sound/Music/Boss2V1.wav.meta
Labels: Coding

#84 Enemy movement and take damage from collision
  BlueProject/Assets/Health.cs
  BlueProject/Assets/Health.cs.meta
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersLaser.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Projectile.cs
  BlueProject/Assets/Projectile.cs.meta
  BlueProject/Assets/Scenes/Main.unity
Labels: Coding

#85 Pooling with rocket
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersLaser.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Prefabs/SpaceItemCONTROL.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scenes/SampleScene.unity
  BlueProject/Assets/Scripts/Health.cs
  BlueProject/Assets/Scripts/Health.cs.meta
  BlueProject/Assets/Scripts/Laser.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManager.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerA.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerA.cs.meta
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerB.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerB.cs.meta
  BlueProject/Assets/Scripts/Pooler/MainPoolA.cs
  BlueProject/Assets/Scripts/Pooler/MainPoolA.cs.meta
  BlueProject/Assets/Scripts/Pooler/MainPoolB.cs
  BlueProject/Assets/Scripts/Pooler/MainPoolB.cs.meta
  BlueProject/Assets/Scripts/Pooler/PoolerA-Laser.asset
  BlueProject/Assets/Scripts/Pooler/PoolerA-Laser.asset.meta
  BlueProject/Assets/Scripts/Pooler/PoolerB-Rocket.asset
  BlueProject/Assets/Scripts/Pooler/PoolerB-Rocket.asset.meta
  BlueProject/Assets/Scripts/Projectile.cs
  BlueProject/Assets/Scripts/Projectile.cs.meta
  BlueProject/Assets/Scripts/Rocket.cs
  BlueProject/Assets/Scripts/ShootLaser.cs
  BlueProject/Assets/Scripts/ShootRocket.cs
  BlueProject/Assets/Scripts/SpaceItems.cs
  BlueProject/Assets/Sound/Music/Boss2V1.wav.meta
Labels: Coding

#80 WIP Enemy Health
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/BasicEnemy.cs
  BlueProject/Assets/Scripts/BasicEnemy.cs.meta
  BlueProject/Assets/Scripts/Enemy.cs
  BlueProject/Assets/Scripts/Enemy.cs.meta
  BlueProject/Assets/Scripts/GameController.cs
Labels: Coding

#93 SpaceShip-Shield
  BlueProject/Assets/Art/forcefield3.fbx
Labels: 3D Model

#95 Force-Field-REDO-3
  BlueProject/Assets/Art/forcefield7.fbx
Labels: 3D Model

#97 shield
  BlueProject/Assets/3Dmesh.meta
  BlueProject/Assets/3Dmesh/Material.002.mat
  BlueProject/Assets/3Dmesh/Material.002.mat.meta
  BlueProject/Assets/3Dmesh/forcefield7.fbx
  BlueProject/Assets/3Dmesh/forcefield7.fbx.meta
  BlueProject/Assets/Art/forcefield3.fbx
  BlueProject/Assets/Art/forcefield7.fbx
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/ShieldCONTROL.prefab
  BlueProject/Assets/Prefabs/ShieldCONTROL.prefab.meta
  BlueProject/Assets/Scenes/Main.unity
Labels: 3D Model, Coding

#100 Create ShotDelay1V1.wav
  BlueProject/Assets/Sound/Effects/ShotDelay1V1.wav
Labels: Audio, SoundFX

#104 Add files via upload
  BlueProject/CD Animation Gif.gif
  BlueProject/CD Animation Sheet.png
  BlueProject/ROCKET_Icon.png
Labels: 2D Sprite

#103 ImprovedPooling and Implemented HP stuff
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayerShipCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersLaser.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Prefabs/ShieldCONTROL.prefab
  BlueProject/Assets/Prefabs/SpaceItemCONTROL.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/GameController.cs
  BlueProject/Assets/Scripts/Health.cs
  BlueProject/Assets/Scripts/Laser.cs
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerA.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerA.cs.meta
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerB.cs
  BlueProject/Assets/Scripts/Pooler/GeneralPoolerManagerB.cs.meta
  BlueProject/Assets/Scripts/Pooler/MainPoolA.cs
  BlueProject/Assets/Scripts/Pooler/MainPoolB.cs
  BlueProject/Assets/Scripts/Pooler/MainPoolB.cs.meta
  BlueProject/Assets/Scripts/Pooler/PoolerA-Laser.asset
  BlueProject/Assets/Scripts/Pooler/PoolerA-Laser.asset.meta
  BlueProject/Assets/Scripts/Pooler/PoolerB-Rocket.asset
  BlueProject/Assets/Scripts/Pooler/PoolerManager.cs
  BlueProject/Assets/Scripts/Pooler/PoolerManager.cs.meta
  BlueProject/Assets/Scripts/Projectile.cs
  BlueProject/Assets/Scripts/Rocket.cs
  BlueProject/Assets/Scripts/ShootLaser.cs
  BlueProject/Assets/Scripts/ShootRocket.cs
  BlueProject/Assets/Sound/Effects.meta
  BlueProject/Assets/Sound/Effects/ShotDelay1V1.wav.meta
  BlueProject/Assets/Sound/Music/World2V1.wav.meta
  BlueProject/Assets/Sprites/LaserFire.png
  BlueProject/ProjectSettings/TagManager.asset
Labels: Coding

#107 Small stuff
  BlueProject/Assets/Prefabs/EnemyDroneCONTROL.prefab
  BlueProject/Assets/Prefabs/PlayersLaser.prefab
  BlueProject/Assets/Prefabs/PlayersRocket.prefab
  BlueProject/Assets/Prefabs/SpaceItemA.prefab
  BlueProject/Assets/Prefabs/SpaceItemA.prefab.meta
  BlueProject/Assets/Prefabs/VFX/ExplosionFX.prefab
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scripts/BGScroller.cs
  BlueProject/Assets/Scripts/EnemyMoves/HardLeft45.asset
  BlueProject/Assets/Scripts/EnemyMoves/HardLeft45.asset.meta
  BlueProject/Assets/Scripts/EnemyMoves/HardRight45.asset
  BlueProject/Assets/Scripts/EnemyMoves/HardRight45.asset.meta
  BlueProject/Assets/Scripts/Health.cs
  BlueProject/Assets/Scripts/Laser.cs
  BlueProject/Assets/Scripts/Player.cs
  BlueProject/Assets/Scripts/Pooler/PoolerManager.cs
  BlueProject/Assets/Scripts/Projectile.cs
  BlueProject/Assets/Scripts/ShootLaser.cs
  BlueProject/Assets/Scripts/ShootRocket.cs
  BlueProject/Assets/Scripts/SpaceItemScroll.cs
  BlueProject/Assets/Scripts/SpaceItems.cs
  BlueProject/Assets/Sprites/TEST-level.png
  BlueProject/Assets/Sprites/TEST-level.png.meta
  BlueProject/Assets/Sprites/blackbackground.png
  BlueProject/Assets/Sprites/blackbackground.png.meta
  BlueProject/Assets/Sprites/galaxy1fixed.png
  BlueProject/Assets/Sprites/galaxy1fixed.png.meta
  BlueProject/Assets/Sprites/stars.png
  BlueProject/Assets/Sprites/stars.png.meta
  BlueProject/Assets/Sprites/stars5.png
  BlueProject/Assets/Sprites/stars5.png.meta
  BlueProject/Assets/Sprites/stars6.png
  BlueProject/Assets/Sprites/stars6.png.meta
  BlueProject/ProjectSettings/TagManager.asset
Labels: Coding, Visual

#108 First DRAFT Level 1
  BlueProject/Assets/Art/CD Animation Gif.gif
  BlueProject/Assets/Art/CD Animation Gif.gif.meta
  BlueProject/Assets/Art/CD Animation Sheet.png
  BlueProject/Assets/Art/CD Animation Sheet.png.meta
  BlueProject/Assets/Art/ROCKET_Icon.png
  BlueProject/Assets/Art/ROCKET_Icon.png.meta
  BlueProject/Assets/Art/TEST-level.png
  BlueProject/Assets/Art/TEST-level.png.meta
  BlueProject/Assets/Prefabs/Level-1.prefab
  BlueProject/Assets/Prefabs/Level-1.prefab.meta
  BlueProject/Assets/Scenes/Main.meta
  BlueProject/Assets/Scenes/Main.unity
  BlueProject/Assets/Scenes/Main/LightingData.asset
  BlueProject/Assets/Scenes/Main/LightingData.asset.meta
  BlueProject/Assets/Scripts/LevelScroller.cs
  BlueProject/Assets/Scripts/LevelScroller.cs.meta
  BlueProject/Assets/Sprites/Level-1.meta
  BlueProject/Assets/Sprites/Level-1/New Material.mat
  BlueProject/Assets/Sprites/Level-1/New Material.mat.meta
  BlueProject/Assets/Sprites/Level-1/tilesheet_TEST.png
  BlueProject/Assets/Sprites/Level-1/tilesheet_TEST.png.meta
  BlueProject/ProjectSettings/QualitySettings.asset
Labels: Visual

#110 missile launch sfx wav files
  BlueProject/Assets/Sound/Effects/MissileLaunch1V1.wav
  BlueProject/Assets/Sound/Effects/MissileLaunch1V2.wav
Labels: Audio, SoundFX

#112 playable prototype
  BlueProject/Assets/Prefabs/SpaceItemA.prefab
  BlueProject/Assets/Scenes/Level-1.unity
  BlueProject/Assets/Scenes/Level-1.unity.meta
  BlueProject/Assets/Scenes/Main.unity.meta
  BlueProject/Assets/Scenes/StartMenu.unity
  BlueProject/ProjectSettings/EditorBuildSettings.asset
Labels: 2D Sprite, 3D Model, Audio, Coding, Music, SoundFX, UI / UX, Visual
